# Generated by Django 4.2.2 on 2024-03-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='History/')),
            ],
        ),
        migrations.CreateModel(
            name='Accreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='accreditation/')),
            ],
        ),
        migrations.CreateModel(
            name='FormerPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('year', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='formerprincipal/')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryofCollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='History/')),
            ],
        ),
        migrations.CreateModel(
            name='MissionVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.CharField(max_length=100)),
                ('vision', models.CharField(max_length=100)),
                ('Corevalues', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RecognitionandAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='recognitionandaward/')),
            ],
        ),
        migrations.CreateModel(
            name='RTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='rti/')),
            ],
        ),
        migrations.CreateModel(
            name='SisterInstituition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=500)),
                ('Address', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='SisterInstituition/')),
            ],
        ),
        migrations.CreateModel(
            name='StrategicPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='strategicplan/')),
            ],
        ),
    ]
