# Generated by Django 4.2.2 on 2024-03-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcollege',
            name='image',
            field=models.ImageField(upload_to='aboutcollege/'),
        ),
        migrations.AlterField(
            model_name='historyofcollege',
            name='image',
            field=models.ImageField(upload_to='history/'),
        ),
        migrations.AlterField(
            model_name='sisterinstituition',
            name='image',
            field=models.ImageField(upload_to='sisterInstituition/'),
        ),
    ]
