# Generated by Django 5.0.3 on 2024-03-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0002_alter_aboutcollege_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyofcollege',
            name='image',
            field=models.ImageField(upload_to='media/history'),
        ),
    ]
